version: '3'
services:
  database:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_PASSWORD: videre
    ports:
      - 5432:5432
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.0
    restart: always
    ports:
      - 8080:8080
