/* @file
 * Copyright (c) 2026, The Videre Project Authors. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
*/

import type { CompiledSql } from '@videre/sql-builder';

import type { PendingSql, Sql } from '@/db/postgres';

export type QueryParams = { [key: string]: any };

export type CompiledQueryBuilder<TParams extends QueryParams> = (
  params: TParams
) => CompiledSql;

export function fromCompiledQuery<
  TRow,
  TParams extends QueryParams = QueryParams
>(
  builder: CompiledQueryBuilder<TParams>
): (sql: Sql, params: TParams) => PendingSql<TRow[]> {
  return (sql, params) => {
    const query = builder(params);

    // Note that query.text is generated by @videre/sql-builder.
    // The query.values are the parameters that will be bound to the query.
    return sql.unsafe(query.text, [...query.values]);
  };
}
