/* @generated by scripts/generate-db-types.mjs */
/* eslint-disable */

import { defineSchema } from "@videre/sql-builder";

export const FORMATS = [
  "Standard",
  "Modern",
  "Pioneer",
  "Vintage",
  "Legacy",
  "Pauper",
  "Premodern",
] as const;

export type FormatType = typeof FORMATS[number];

export const EVENTS = [
  "League",
  "Preliminary",
  "Challenge",
  "Showcase",
  "Qualifier",
] as const;

export type EventType = typeof EVENTS[number];

export const RESULTS = [
  "win",
  "loss",
  "draw",
] as const;

export type ResultType = typeof RESULTS[number];

export type RecordType = `${number}-${number}-${number}`;

export type CardQuantityPair = {
  id: number;
  name: string;
  quantity: number;
};

export type GameResult = {
  id: number;
  result: ResultType;
};

export const TABLE_COLUMNS = {
  "archetypes": [
    "id",
    "deck_id",
    "name",
    "archetype",
    "archetype_id",
  ],
  "card_catalog_variants": [
    "catalog_id",
    "card_id",
    "variant_type",
    "set_code",
    "name",
    "name_normalized",
    "card_texture_number",
    "is_foil",
    "is_token",
    "first_seen_at",
    "last_seen_at",
    "raw",
  ],
  "card_faces": [
    "card_id",
    "face_index",
    "source_catalog_id",
    "name",
    "name_normalized",
    "colors",
    "color_mask",
    "mana_value",
    "flavor_text",
    "mana_cost",
    "type_line",
    "oracle_text",
    "supertypes",
    "card_types",
    "subtypes",
    "power",
    "toughness",
    "loyalty",
    "defense",
    "artist",
    "art_id",
    "raw",
    "search_vector",
    "card_type_mask",
  ],
  "card_legalities": [
    "oracle_id",
    "format_code",
    "status",
    "source_rule_set_id",
    "first_seen_at",
    "last_seen_at",
  ],
  "cards": [
    "id",
    "oracle_id",
    "set_code",
    "collector_number",
    "name",
    "name_normalized",
    "art_id",
    "artist",
    "card_texture_number",
    "other_face_texture_number",
    "split_card_ids",
    "split_parent_card_id",
    "split_other_card_id",
    "colors",
    "color_identity",
    "color_mask",
    "color_identity_mask",
    "mana_value",
    "flavor_text",
    "mana_cost",
    "type_line",
    "oracle_text",
    "supertypes",
    "card_types",
    "subtypes",
    "power",
    "toughness",
    "loyalty",
    "defense",
    "rarity",
    "frame_style",
    "promo_label",
    "has_activated_ability",
    "should_work",
    "is_foil",
    "is_token",
    "first_seen_at",
    "last_seen_at",
    "raw",
    "search_vector",
    "card_type_mask",
  ],
  "decks": [
    "id",
    "event_id",
    "player",
    "mainboard",
    "sideboard",
  ],
  "events": [
    "id",
    "name",
    "date",
    "format",
    "kind",
    "rounds",
    "players",
  ],
  "formats": [
    "code",
    "name",
    "display_order",
  ],
  "matches": [
    "id",
    "event_id",
    "round",
    "player",
    "opponent",
    "record",
    "result",
    "isbye",
    "games",
  ],
  "oracle_cards": [
    "id",
    "name",
    "name_normalized",
    "mana_cost",
    "mana_value",
    "type_line",
    "oracle_text",
    "colors",
    "color_identity",
    "color_mask",
    "color_identity_mask",
    "supertypes",
    "card_types",
    "subtypes",
    "power",
    "toughness",
    "loyalty",
    "defense",
    "is_token",
    "first_seen_at",
    "last_seen_at",
    "search_vector",
    "card_type_mask",
  ],
  "pending_image_sync": [
    "catalog_id",
    "reason",
    "first_seen_at",
    "last_seen_at",
  ],
  "players": [
    "id",
    "name",
  ],
  "products": [
    "id",
    "set_code",
    "name",
    "name_normalized",
    "object_type",
    "texture_number",
    "is_tradable",
    "first_seen_at",
    "last_seen_at",
    "raw",
    "search_vector",
  ],
  "sets": [
    "code",
    "name",
    "release_date",
    "age",
    "set_type",
    "first_seen_at",
    "last_seen_at",
    "raw",
  ],
  "standings": [
    "event_id",
    "rank",
    "player",
    "record",
    "points",
    "omwp",
    "gwp",
    "owp",
  ],
} as const;

export type TableName = keyof typeof TABLE_COLUMNS;

export type TableColumn<T extends TableName> = typeof TABLE_COLUMNS[T][number];

export const DATABASE_SCHEMA = defineSchema(TABLE_COLUMNS);

export const table = DATABASE_SCHEMA.table;

export const CARD_COLORS = [
  {
    symbol: "W",
    name: "WHITE",
    bit: 1,
  },
  {
    symbol: "U",
    name: "BLUE",
    bit: 2,
  },
  {
    symbol: "B",
    name: "BLACK",
    bit: 4,
  },
  {
    symbol: "R",
    name: "RED",
    bit: 8,
  },
  {
    symbol: "G",
    name: "GREEN",
    bit: 16,
  },
] as const;

export type CardColor = typeof CARD_COLORS[number];

export const CARD_RARITIES = [
  "basic land",
  "bonus",
  "common",
  "mythic",
  "promo",
  "rare",
  "token",
  "uncommon",
] as const;

export type CardRarity = typeof CARD_RARITIES[number];

export const CARD_RARITY_LADDER = [
  "common",
  "uncommon",
  "rare",
  "mythic",
] as const;

export type RankedCardRarity = typeof CARD_RARITY_LADDER[number];

export const CARD_RARITY_ALIASES = [
  {
    alias: "basic",
    rarity: "basic land",
  },
  {
    alias: "basicland",
    rarity: "basic land",
  },
  {
    alias: "c",
    rarity: "common",
  },
  {
    alias: "m",
    rarity: "mythic",
  },
  {
    alias: "mythic rare",
    rarity: "mythic",
  },
  {
    alias: "mythicrare",
    rarity: "mythic",
  },
  {
    alias: "r",
    rarity: "rare",
  },
  {
    alias: "u",
    rarity: "uncommon",
  },
] as const;

export type CardRarityAlias = typeof CARD_RARITY_ALIASES[number];
