name = "videre-api"
main = "./src/index.ts"
compatibility_date = "2023-12-18"
compatibility_flags = [ "nodejs_compat" ]
routes = [
  { pattern = "api.videreproject.com", custom_domain = true }
]

[vars]
PGHOST = "worker-db.videreproject.com"
PGPORT = "5432"
PGDATABASE = "mtgo"
PGUSER = "api"
PGSSL = "true"
CACHE_VERSION = "1"

[secrets]
required = [ "PGPASSWORD", "CF_CLIENT_ID", "CF_CLIENT_SECRET" ]
